---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Äventuren 2016"
keywords:    "Äventuren, aventuren, scout, utmanare, rover, ledare, arrangemang, tävling, skåne"
description: "En poängtävlan för för Utmanarscouter, roverscouter och ledare"
source_link: "https://petterl.github.io/aventuren2016"
favicon:     "img/favicon-morkbla.ico" #put a path like: "img/favicon.ico"
touch_icon:  "img/scoutlilja-bla.png" #put a path like: "img/apple-touch-icon.png"
google_analytics_key: "UA-70259114-1" ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  darkgreen: '#78AB46'
  red:       '#cf3f4f'

kramdown:
  auto_ids:  false

